[package]
name = "kriya_spot_dex"
version = "1.0.0"
published-at = "0xa00e94ca43888e93c7c2956281ac6e23ec1f31960913a34d10dfb5b711f5f4d6"

[addresses]
kriya = "0xa00e94ca43888e93c7c2956281ac6e23ec1f31960913a34d10dfb5b711f5f4d6"
std = "0x1"
sui =  "0x2"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet" }
